config/routes.rb
Rails.application.routes.draw do
  
	root "ideas#index" #routing for home page

	resources :ideas

	get 'about' => 'static_pages#about'
	get 'random' => 'static_pages#random'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
	validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

	def index
		  @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
	end

	def create 
		@idea = Idea.create(idea_params)
		redirect_to root_path
	end

	def edit 
		@idea = Idea.find(params[:id])
	end

	def update
  		@idea = Idea.find(params[:id])
  		if @idea.update(idea_params)
    		redirect_to root_path
  		else
    		redirect_to edit_idea_path(params[:id])
  		end
	end

	def destroy
  		@idea = Idea.find(params[:id])
  		@idea.destroy
  		redirect_to root_path
	end
	
	private 

	def idea_params
		params.require(:idea).permit(:description,:author)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def about

  	end

  	def random
  		 @idea = Idea.order("RANDOM()").first
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= simple_form_for @idea, method: :patch do |f| %>
<%= f.input :description %>
  <%= f.input :author %>
  <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    <i class="fa fa-pencil" aria-hidden="true"></i> Post
  <% end %>
<% end %>

app/views/ideas/index.html.erb
  <% @ideas.each do |idea| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <blockquote>
          <p><%= idea.description %></p>
          <small>by <%= idea.author %></small>
        </blockquote> 
        <br>

        <div class="btn-group" role="group">
          <%= link_to idea_path(idea) ,method: :delete ,class: 'btn btn-sm btn-danger',data: {confirm: "Are you sure?"} do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          <% end %>
          <%= link_to edit_idea_path(idea) ,class: 'btn btn-sm btn-success' do %>
            <i class="fa fa-pencil-square" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  
<div class = "text-center">
  <%= will_paginate @ideas, class: 'apple_pagination' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator | Share Your Idea</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  	<div id = "wrap">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" style="color: #337AB7;"><i class="fa fa-lightbulb-o  fa-2x" aria-hidden="true"></i>Ideator</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse text-center" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'All Ideas', root_path %></li>
          <li><%= link_to 'Inspire Me', random_path %></li>
          <li><%=link_to 'About',about_path %></li>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Post Your Idea</h4>
      </div>
      <%= simple_form_for Idea.new do |f| %>
        <div class="modal-body">
          <%= f.input :description %>
          <%= f.input :author %>
        </div>      
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
              <i class="fa fa-pencil" aria-hidden="true"></i> Post
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="is-container">
  <div class = "container">
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <%= yield %>
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </div>
 </div> 
</div>

<footer class="footer text-center">
  <div class="container">
    <div class = "row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class = "col-xs-12 col-md-6">
            <h4>Contact</h4>
            <p>rabingaire20@gmail.com</p>
            <p><a href="http://rabingaire.com.np">rabingaire.com.np</a></p>
          </div>
          <div class = "col-xs-12 col-md-6">
            <h4>© TECHRISE 2016</h4>
            <p>All Rights Reserved</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
      </div>
  </div>
</footer>
<div class = "col-xs-12 col-md-12 is-findus text-center">
  <h4>Find Me On</h4>
  <div class="social-buttons">
    <a href = "https://www.facebook.com/robbengaire"><i class="fa fa-facebook-official social fa-2x" ></i></a>
    <a href = "https://twitter.com/rabin_gaire"><i class="fa fa-twitter-square social fa-2x" ></i></a>
    <a href = "https://np.linkedin.com/in/rabin-gaire-b4187a95"><i class="fa fa-linkedin-square social fa-2x" ></i></a>
  </div>
</div>

<link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<script src="https://use.fontawesome.com/86c49aa805.js"></script>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

<h4>Share you ideas with the world and find others.</h4>

<p>
  We people have around 50,000-70,000 thoughts per day. They Just Vanish away.
  Those Ideas could make a better future/world. Let's Share them with others.
</p>

<p>
  Our Platform Helps you to share idea with others :) 
  <br/>Have a thought well you have got IDEATOR.
</p>

app/views/static_pages/random.html.erb
<% if @idea.present? %>
  <div class="refresh-btn text-center">
    <%= link_to  random_path, class: 'btn btn-primary' do %>
      <i class="fa fa-refresh" aria-hidden="true"></i> Inspire Me 
    <% end %>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
        <p><%= @idea.description %></p>
        <small>by <%= @idea.author %></small>
      </blockquote>
        
      <br>

      <div class="btn-group" role="group">
        <%= link_to  idea_path(@idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        <% end %>
        <%= link_to  edit_idea_path(@idea), class: 'btn btn-sm btn-success' do  %>
          <i class="fa fa-pencil-square" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  </div>
  <% else %>
  <h4>No ideas have been shared. Add one <%= link_to 'here', root_path %></h4>

<% end %>